// <auto-generated />
namespace QualityControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tradeuserid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tradeuserid));
        
        string IMigrationMetadata.Id
        {
            get { return "201509230727019_trade-userid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
