// <auto-generated />
namespace QualityControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sgsvirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sgsvirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201509241231024_sgsvirtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
